name: CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node

            - name: Install Dependencies
              run: |
                  npm install
                  bower install
                  grunt
